// Algorithm explanations for the visualizer
export const ALGORITHM_EXPLANATIONS = {
    bubble: { name: 'Bubble Sort', description: 'Compares adjacent elements and swaps them if they are in the wrong order. This process is repeated until the list is sorted, with the largest elements "bubbling" to the end.', time: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' }, space: 'O(1)' },
    selection: { name: 'Selection Sort', description: 'Repeatedly finds the minimum element from the unsorted part of the array and puts it at the beginning. It maintains a sorted and an unsorted subarray.', time: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)' }, space: 'O(1)' },
    insertion: { name: 'Insertion Sort', description: 'Builds the final sorted array one item at a time. It iterates through the input elements and inserts each element into its correct position in the sorted part of the array.', time: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' }, space: 'O(1)' },
    merge: { name: 'Merge Sort', description: 'A divide-and-conquer algorithm that divides the array into two halves, recursively sorts them, and then merges the two sorted halves.', time: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)' }, space: 'O(n)' },
    quick: { name: 'Quick Sort', description: 'A divide-and-conquer algorithm that picks a \'pivot\' element and partitions the other elements into two sub-arrays, according to whether they are less than or greater than the pivot.', time: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)' }, space: 'O(log n)' },
    heap: { name: 'Heap Sort', description: 'A comparison-based algorithm that uses a binary heap data structure. It first builds a max-heap from the input data, then repeatedly extracts the maximum element from the heap and places it at the end of the sorted array.', time: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)' }, space: 'O(1)' },
    radix: { name: 'Radix Sort', description: 'A non-comparative integer sorting algorithm that sorts data with integer keys by grouping keys by the individual digits which share the same significant position and value.', time: { best: 'O(nk)', average: 'O(nk)', worst: 'O(nk)' }, space: 'O(n+k)' },
    pancake: { name: 'Pancake Sort', description: 'The only operation is to "flip" a prefix of the array. It works by finding the largest unsorted element, flipping it to the front, and then flipping it to its correct final position.', time: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' }, space: 'O(1)' },
    stooge: { name: 'Stooge Sort', description: 'A recursive sorting algorithm with a high time complexity. It works by recursively sorting the first 2/3, then the last 2/3, and then the first 2/3 again to ensure the array is sorted.', time: { best: 'O(n^2.71)', average: 'O(n^2.71)', worst: 'O(n^2.71)' }, space: 'O(log n)' },
};
